services:
  nginx:
    image: nginx:alpine
    ports:
      - "86:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/html  
    networks:
      - goals_php_web
    depends_on:
      - frontend    

  frontend:
    build:
      #DIRECTORY CONTEXT
      context: ./build/php
      #PATH TO DIR WHERE IS THE DOCKERFILE
      dockerfile: Dockerfile
      #ADD ADDITIONAL CONTEXT TO USE IN DOCKERFILE WITH --from=name 
      additional_contexts:
        resource_code:  ./code
      #BUILD ARGUMENTS
      args:
        PHP_VERSION: "8.3-fpm"
    expose:
      - 9000
    ports:
      - "5173:5173"  
    networks:
      - goals_php_web
      - goals_db_php
    volumes:
      - ./code:/var/www/html  
    depends_on:
      - db_postgres  

  db_postgres:
    image: postgres
    shm_size: 125mb
    networks:
      - goals_db_php
    ports:
      - "5433:5432"
    env_file:
      - ./prod.env  
    volumes:
      - ./db_postgres_volume:/var/lib/postgresql/data

networks:
  goals_php_web:
    driver: bridge
  goals_db_php:
    driver: bridge  
